name: Test Code
on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger the action on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Datadog Agent
        uses: datadog/agent-github-action@v1.3
        with:
          api_key: ${{ secrets.DD_API_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make tests
