name: Datadog Integration

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger the action on

jobs:
  datadog_integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Datadog Agent
        run: |
          echo "${{ secrets.DD_API_KEY }}" > auth_token
          docker run -d --name datadog-agent \
            -e DD_API_KEY="`cat auth_token`" \
            -v $PWD/auth_token:/etc/datadog-agent/auth_token \
            datadog/agent:latest

      - name: Run Tests and Collect Metrics
        run: |
          # Add the command to build and execute your project here
          # For example, if you have a Python script, use: python path/to/your/script.py
          # If you have a shell script, use: bash path/to/your/script.sh

          # Send custom metrics to Datadog using the DogStatsD client
          docker run --rm --name datadog-statsd \
            -e DD_API_KEY="`cat auth_token`" \
            datadog/dogstatsd:latest statsd.increment 'test.run'

      # Add other steps for your build/test/deploy process here.

      - name: Cleanup Datadog Agent and StatsD container
        run: |
          docker stop datadog-agent
          docker stop datadog-statsd
          docker rm datadog-agent
          docker rm datadog-statsd
