name: Datadog Integration

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger the action on

jobs:
  datadog_integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Datadog Agent
        run: |
          echo "${{ secrets.DD_API_KEY }}" > auth_token
          docker run -d --name datadog-agent \
            -e DD_API_KEY="`cat auth_token`" \
            -v $PWD/auth_token:/etc/datadog-agent/auth_token \
            datadog/agent:latest

      # Add other steps for your build/test/deploy process here.
      # For example:
      # - name: Build and Test
      #   run: make tests

      - name: Cleanup Datadog Agent container
        run: docker stop datadog-agent && docker rm datadog-agent
